import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ReactQueryProvider from "@/providers/react-query-provider";
import NextThemeProvider from "@/providers/next-theme-provider";
import { Layout } from "@/components/layout";
import { Toaster } from "@/components/ui/sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta property="og:title" content="PetPedia" />
        <meta
          property="og:description"
          content="A place where you can find all the pets you need"
        />
        <meta property="og:url" content="https://pet-pedia.vercel.app/" />
        <meta property="og:type" content="website" />
      </head>
      <body className={inter.className}>
        <ReactQueryProvider>
          <NextThemeProvider>
            <Layout>{children}</Layout>
          </NextThemeProvider>
        </ReactQueryProvider>
        <Toaster richColors />
      </body>
    </html>
  );
}
